# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

PYTHON_PYLINT_PRE_COMMANDS:
  # Help pylint understand pydantic models
  - command: pip install pylint-pydantic
    venv: pylint
    continue_if_failed: false

PYTHON_PYLINT_ARGUMENTS:
  # Disable import checks because it needs all the Python dependencies installed in the linter
  # https://github.com/oxsecurity/megalinter/issues/2030
  - "--disable=E0401,E0611"
  # Help pylint understand pydantic models
  - "--load-plugins=pylint_pydantic"
PYTHON_FLAKE8_ARGUMENTS:
  - "--max-line-length=100"

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT
  - PYTHON_MYPY
  - REPOSITORY_CHECKOV
  - COPYPASTE_JSCPD

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

PYTHON_BANDIT_FILTER_REGEX_EXCLUDE: test_
