# A basic docker compose file for running the current version of plejd-mqtt-ha

version: "3.8"
services:
  plejd:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/:/data/
    network_mode: host
    privileged: true
